name: Notify Discord of a New Commit

on:
  push:
    branches:
      - main

env:
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Send notification to Discord
        uses: ${REPO_OWNER}/${REPO_NAME}/discord-action@main
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: '**${{ github.actor }}** pushed [${{ github.sha }}](https://github.com/${REPO_OWNER}/${REPO_NAME}/commit/${{ github.sha }}) to **${{ github.ref_name }}**'
